# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "telnyx"

gem "sinatra"

gem "dotenv"

gem "ostruct"

gem "json"

gem 'aws-sdk'

gem 'down'